artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/hrishikesh147/MLPROJECT9_MLFLOW/raw/main/winequality-red.zip
              #https://github.com/hrishikesh147/MLPROJECT9_COT_MLFLOW/raw/main/winequalityN.zip
  #           https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip 
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt  #will return true or false, if false we wont go ahead as data format is wrong

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv
