artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/hrishikesh147/MLPROJECT9_COT_MLFLOW/raw/main/winequalityN.zip
  #           https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip 
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
